### ISSUE TITLE
Create user stories

### ISSUE THREAD

**Issue by WeilonYing** [WeilonYing/compclub-web#12]
Create some scenarios where users and volunteers may navigate and use the website.

**Comment by mehri-amin** [comment]
I've written up a few user stories on trello here: https://trello.com/b/aCKqyyQf/compclub
Not sure the difference between admin and volunteer so if I wrote something that a volunteer isn't allowed to do i.e. add/delete an event listing then I meant it for admin!

**Comment by WeilonYing** [comment]
Awesome. Thank you!
