### ISSUE TITLE
Using external libraries to handle recurring events

### ISSUE THREAD

**Issue by lamcw** [WeilonYing/compclub-web#35]
Currently we plan to create one-off/weekly workshops by dynamically adding forms to a formset and storing them independently in the database, i.e., each workshops may have no relationships with the next/previous occurrence. I feel like this would be a big challenge for us to develop a bug-free, clean solution to query for workshop time and displaying them in our website. For example, generating workshops with a given pattern (weekly, biweekly, twice a week, etc.) could be difficult to implement. Users may want to exclude public holiday when generating workshop time. Do you think it's a good idea to use an existing solution in our project?

A few options I found on GitHub:
* [django-recurrence](https://github.com/django-recurrence/django-recurrence) - includes form widget, [well-documented](https://django-recurrence.readthedocs.io/)
* [django-eventtools](https://github.com/gregplaysguitar/django-eventtools) - lightweight, but no proper docs, does not support [occurrence cancellations or modifications](https://github.com/gregplaysguitar/django-eventtools#occurrence-cancellations-or-modifications)

Both supports custom repeating rules.

For working day support, see django-recurrence/django-recurrence#83

**Comment by WeilonYing** [comment]
This looks to be a good idea. I'd go with django-recurrence, mainly for its better documentation. You're free to use it in the project.

**Comment by WeilonYing** [comment]
We're able to do this without using external libraries, so no need for this issue now.
